# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbelt', '0006_auto_20170224_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='datefrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dateto',
            field=models.DateField(),
        ),
    ]
